env:
  browser: true
  es2021: true
extends:
  - google
  - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "prettier"
rules: { "prettier/prettier": "error", "new-cap": "off" }
