# syntax=docker/dockerfile:1

FROM golang:1.19-alpine

WORKDIR /app

ENV STARTON_API_KEY=sk_live_22eeb1f2-234b-4685-b831-269368f0d8d1

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . ./ 

RUN go build -o /upload-cid

EXPOSE 8080

CMD [ "/upload-cid" ]
